version: '2'
volumes:
  swift_build:
services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
  test:
    build: .
    volumes:
      - .:/app
      - swift_build:/app/.build
    command: swift test
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
